#!/bin/sh
setxkbmap -option caps:swapescape
setxkbmap -option altwin:menu_win
setxkbmap -layout us,gr -option grp:alt_shift_toggle

xwallpaper --stretch "$XDG_DATA_HOME/bg"
xrdb -merge "$XDG_CONFIG_HOME/X11/Xresources"
[ -n "$xrdbpid" ] && wait "$xrdbpid"

xrandr 2>&1 >/dev/null								\
	--dpi 96								\
	--output $(xrandr | egrep 'HDMI-[0-9]+ connected' | awk '{print $1;}')	\
	--rotate left								\

sxhkd &
slstatus &
exec dwm
