#!/bin/sh

# Desktops
bspc monitor -d 1 2 3 4

# Options
bspc config window_gap			7
bspc config top_padding			0
bspc config split_ratio         0.5
bspc config border_width		3
bspc config single_monocle		true
bspc config gapless_monocle     true
bspc config focus_by_distance	true
bspc config borderless_monocle  true
bspc config focus_follows_pointer true

# Rules
bspc rule -a popup_term state=floating hidden=on
bspc rule -a popup_file_manager state=floating hidden=on

# Scratchpads
kitty --class=popup_term &
kitty --class=popup_file_manager -- lf &

# Polybar
killall -q polybar
polybar-git -r main &
